# Generated by Django 5.0 on 2026-08-17 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
