# Generated by Django 5.0 on 2026-04-27 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('species', models.CharField(choices=[('dog', 'سگ'), ('cat', 'گربه'), ('bird', 'پرنده'), ('rabbit', 'خرگوش'), ('fish', 'ماهی'), ('other', 'سایر')], max_length=20, verbose_name='گونه')),
                ('breed', models.CharField(blank=True, max_length=100, verbose_name='نژاد')),
                ('gender', models.CharField(choices=[('male', 'نر'), ('female', 'ماده'), ('unknown', 'نامشخص')], max_length=20, verbose_name='جنسیت')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='وزن')),
                ('color', models.CharField(max_length=50, verbose_name='رنگ')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pets/photos/', verbose_name='عکس حیوان')),
                ('microchip_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='کد میکروچیپ')),
                ('is_neutered', models.BooleanField(default=False, verbose_name='عقیم شده؟')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='owners.owner', verbose_name='صاحب')),
            ],
            options={
                'verbose_name': 'حیوان خانگی',
                'verbose_name_plural': 'حیوانات خانگی',
                'ordering': ['name'],
            },
        ),
    ]
