# Generated by Django 5.0 on 2026-08-24 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_tag_posttag_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categoty',
            new_name='category',
        ),
    ]
