# Generated by Django 5.0 on 2026-04-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام واکسن')),
                ('date_given', models.DateField(verbose_name='تاریخ تزریق')),
                ('next_due', models.DateField(blank=True, null=True, verbose_name='نوبت بعدی')),
                ('batch_number', models.CharField(blank=True, max_length=50, verbose_name='شماره سری')),
                ('administered_by', models.CharField(blank=True, max_length=100, verbose_name='تزریق کننده')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'واکسن',
                'verbose_name_plural': 'واکسن\u200cها',
                'ordering': ['-date_given'],
            },
        ),
        migrations.CreateModel(
            name='VetVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ویزیت')),
                ('visit_type', models.CharField(choices=[('checkup', 'معاینه عمومی'), ('emergency', 'اورژانس'), ('vaccination', 'واکسیناسیون'), ('surgery', 'جراحی'), ('followup', 'پیگیری')], default='checkup', max_length=20, verbose_name='نوع ویزیت')),
                ('vet_name', models.CharField(blank=True, max_length=100, verbose_name='نام دامپزشک')),
                ('weight_at_visit', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='وزن هنگام ویزیت')),
                ('diagnosis', models.TextField(blank=True, verbose_name='تشخیص')),
                ('treatment', models.TextField(blank=True, verbose_name='درمان')),
                ('prescribed_medicines', models.TextField(blank=True, verbose_name='داروهای تجویزی')),
                ('cost', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه (تومان)')),
                ('next_appointment', models.DateTimeField(blank=True, null=True, verbose_name='نوبت بعدی')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ویزیت',
                'verbose_name_plural': 'ویزیت\u200cها',
                'ordering': ['-visit_date'],
            },
        ),
    ]
