# Generated by Django 5.0 on 2026-04-27 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='pets.pet', verbose_name='حیوان'),
        ),
        migrations.AddField(
            model_name='vetvisit',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='pets.pet', verbose_name='حیوان'),
        ),
    ]
